title: "Sinduja Rangarajan"
description: "Investigative data journalist and data developer"
url: "https://cynduja.github.io"
baseurl: "/sinduja.github.io"   # must match the repo name
markdown: kramdown
permalink: pretty

collections:
  projects:
    output: true

exclude:
  - README.md
